### ISSUE TITLE
[BUG]~Emotes not working on purpur

### ISSUE THREAD

**Issue by itsMarkiS** [HibiscusMC/HMCCosmetics#112]
### Plugin Version

2.4.0

### Server Version

Purpur-1968 (MC: 1.19.4)*

### Issue description

[22:10:26 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cosmetic' in plugin HMCCosmetics v2.4.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:920) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2383) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2343) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1968]        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/WrappedDataValue
        at com.hibiscusmc.hmccosmetics.util.packets.PacketManager.sendInvisibilityPacket(PacketManager.java:144) ~[HMCCosmeticsRemapped-2.4.0.jar:?]
        at com.hibiscusmc.hmccosmetics.user.manager.UserEmoteModel.playAnimation(UserEmoteModel.java:82) ~[HMCCosmeticsRemapped-2.4.0.jar:?]
        at com.hibiscusmc.hmccosmetics.user.manager.UserEmoteManager.playEmote(UserEmoteManager.java:38) ~[HMCCosmeticsRemapped-2.4.0.jar:?]
        at com.hibiscusmc.hmccosmetics.command.CosmeticCommand.onCommand(CosmeticCommand.java:483) ~[HMCCosmeticsRemapped-2.4.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.wrappers.WrappedDataValue
        at com.hibiscusmc.hmccosmetics.util.packets.PacketManager.sendInvisibilityPacket(PacketManager.java:144) ~[HMCCosmeticsRemapped-2.4.0.jar:?]
        at com.hibiscusmc.hmccosmetics.user.manager.UserEmoteModel.playAnimation(UserEmoteModel.java:82) ~[HMCCosmeticsRemapped-2.4.0.jar:?]
        at com.hibiscusmc.hmccosmetics.user.manager.UserEmoteManager.playEmote(UserEmoteManager.java:38) ~[HMCCosmeticsRemapped-2.4.0.jar:?]
        at com.hibiscusmc.hmccosmetics.command.CosmeticCommand.onCommand(CosmeticCommand.java:483) ~[HMCCosmeticsRemapped-2.4.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 23 more

### Steps to reproduce

1 - play a emote
or use the command "/cosmetic playemote <emote>"

### Issue priority

Low (slightly annoying)

### Other Versions

oraxen-1.156.2
Model-Engine-R3.1.7
HMCColor-0.7 <?>

**Comment by LoJoSho** [comment]
What's your ProtocolLib version? Make sure it's at least 5.0+. It seems like it's trying to find a class that does not exist on your server.

> Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/WrappedDataValue
