### ISSUE TITLE
emotes not work

### ISSUE THREAD

**Issue by X1nDi** [HibiscusMC/HMCCosmetics#149]
### Plugin Version

2.7.2

### Server Version

purpur-2044-1.20.1

### Issue description

when i use emote:
[10:19:35 WARN]: java.util.NoSuchElementException
[10:19:35 WARN]:        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:433)
[10:19:35 WARN]:        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:473)
[10:19:35 WARN]:        at HMCCosmeticsRemapped-2.7.2.jar//com.hisbiscusmc.hmccosmetics.playeranimator.nms.v1_20_R1.NMSHandler_v1_20_R1.getTexture(NMSHandler_v1_20_R1.java:85)
[10:19:35 WARN]:        at HMCCosmeticsRemapped-2.7.2.jar//com.hisbiscusmc.hmccosmetics.playeranimator.api.model.player.PlayerModel.<init>(PlayerModel.java:38)
[10:19:35 WARN]:        at HMCCosmeticsRemapped-2.7.2.jar//com.hibiscusmc.hmccosmetics.user.manager.UserEmoteModel.<init>(UserEmoteModel.java:30)
[10:19:35 WARN]:        at HMCCosmeticsRemapped-2.7.2.jar//com.hibiscusmc.hmccosmetics.user.manager.UserEmoteManager.playEmote(UserEmoteManager.java:44)
[10:19:35 WARN]:        at HMCCosmeticsRemapped-2.7.2.jar//com.hibiscusmc.hmccosmetics.user.manager.UserEmoteManager.playEmote(UserEmoteManager.java:30)
[10:19:35 WARN]:        at HMCCosmeticsRemapped-2.7.2.jar//com.hibiscusmc.hmccosmetics.cosmetic.types.CosmeticEmoteType.run(CosmeticEmoteType.java:28)
[10:19:35 WARN]:        at HMCCosmeticsRemapped-2.7.2.jar//com.hibiscusmc.hmccosmetics.listener.PlayerGameListener.onPlayerOffhandSwap(PlayerGameListener.java:285)
[10:19:35 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1140.execute(Unknown Source)
[10:19:35 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[10:19:35 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[10:19:35 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:19:35 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[10:19:35 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[10:19:35 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[10:19:35 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1948)
[10:19:35 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[10:19:35 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[10:19:35 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[10:19:35 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:19:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[10:19:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[10:19:35 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)
[10:19:35 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[10:19:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[10:19:35 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1343)
[10:19:35 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)
[10:19:35 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[10:19:35 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1413)
[10:19:35 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[10:19:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[10:19:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

### Steps to reproduce

just use emote

### Issue priority

High (immediate attention needed)

### Other Versions

ModelEngine-R3.1.9
Oraxen-1.170.1

**Comment by LoJoSho** [comment]
Emotes are a [deprecated feature](https://docs.hibiscusmc.com/hmccosmetics%20remapped/cosmetics/Emotes) that does not work on the latest versions.

**Comment by X1nDi** [comment]
what should i do for emotes work

**Comment by X1nDi** [comment]
it says that emotions don't work on versions 1.20.2>, but I have version 1.20.1

**Comment by X1nDi** [comment]
@LoJoSho

**Comment by LoJoSho** [comment]
There's no work being done on the emote section of the plugin and it'll be removed in a later version. 

From the error you sent, it looks like the library is searching for a class that's not available to it anymore, nothing we can really do about that.
