### ISSUE TITLE
[BUG] ISSUE WARDROBE WITH 1.18.2

### ISSUE THREAD

**Issue by niriaaa** [HibiscusMC/HMCCosmetics#20]
### I have checked...

- [X] I am using the latest version of HMCCosmetics
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

I report this bug on discord, and we tell me to report here.

Hello, i was configure the wardrobe systeme
and i had this error when i try

```
[14:34:35] [Craft Scheduler Thread - 95 - HMCCosmetics/WARN]: [HMCCosmetics] Plugin HMCCosmetics v1.10.3 generated an exception while executing task 4658
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/entity/CraftPlayer
    at io.github.fisher2911.nms.PacketHelper_1_18_R1.getCopyProfile(PacketHelper_1_18_R1.java:100) ~[HMCCosmetics.jar:?]
    at io.github.fisher2911.nms.PacketHelper_1_18_R1.getPlayerInfoPacket(PacketHelper_1_18_R1.java:41) ~[HMCCosmetics.jar:?]
    at io.github.fisher2911.hmccosmetics.packet.PacketManager.getFakePlayerInfoPacket(PacketManager.java:214) ~[HMCCosmetics.jar:?]
    at io.github.fisher2911.hmccosmetics.user.Wardrobe.spawnFakePlayer(Wardrobe.java:97) ~[HMCCosmetics.jar:?]
    at io.github.fisher2911.hmccosmetics.command.CosmeticsCommand.lambda$openWardrobe$1(CosmeticsCommand.java:295) ~[HMCCosmetics.jar:?]
    at io.github.fisher2911.hmccosmetics.task.TaskChain.lambda$run$0(TaskChain.java:41) ~[HMCCosmetics.jar:?]
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1586]
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1586]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1586]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
    ... 12 more
[14:34:41] [Craft Scheduler Thread - 90 - HMCCosmetics/WARN]: [HMCCosmetics] Plugin HMCCosmetics v1.10.3 generated an exception while executing task 4665
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/entity/CraftPlayer
    at io.github.fisher2911.nms.PacketHelper_1_18_R1.getCopyProfile(PacketHelper_1_18_R1.java:100) ~[HMCCosmetics.jar:?]
    at io.github.fisher2911.nms.PacketHelper_1_18_R1.getPlayerRemovePacket(PacketHelper_1_18_R1.java:68) ~[HMCCosmetics.jar:?]
    at io.github.fisher2911.hmccosmetics.packet.PacketManager.getRemovePlayerPacket(PacketManager.java:226) ~[HMCCosmetics.jar:?]
    at io.github.fisher2911.hmccosmetics.user.Wardrobe.lambda$despawnFakePlayer$5(Wardrobe.java:131) ~[HMCCosmetics.jar:?]
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1586]
    at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1586]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1586]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer
```

### Steps to reproduce

configure wardrobe and test.

### Plugin Version

Last version

### ModelEngine Version

Last version

### Server Version

Last version 1.18.2 PURPUR

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by lucian929** [comment]
Fixed in 1.11.0-BETA-2
